### ISSUE TITLE
Sync changes from Kyma NATS chart to nats-manager NATS chart.

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/nats-manager#122]
**Description**
Make sure that possible new changes on the Kyma side are synced to nats-manager.

When we enable a module using `kyma alpha enable module nats -c fast -n kyma-system`, the lifecycle manager by default creates a NAT CR in the cluster. The default CR is configured [here](https://github.com/kyma-project/nats-manager/blob/main/config/samples/default.yaml).

**Note**
Small upgrade hickups like helm chart issues should be fixed within this ticket. Big changes should be a follow up ticket.

**Tasks:**
- [x] Synchronise changes from [Kyma NATS chart](https://github.com/kyma-project/kyma/tree/main/resources/eventing/charts/nats) to [nats-manager NATS chart](https://github.com/kyma-project/nats-manager/tree/main/resources/nats).
- [x] Bump all the NATS images tag to same as in kyma NATS chart:
    - [x] Config Reloader
    - [x] Metrics Exporter
    - [x] NATS Server 
- [x]  Make sure that the default CR is correct for upgrade from kyma to nats-manager.
- [x] Test the upgrade from kyma to nats-manager on a working Kyma cluster by following the steps from: [link](https://github.com/kyma-project/nats-manager/issues/77).
   - [x] Fast-integration test
   - [x] Stream and consumers are not recreated by the upgrade
   - [x] Check that the pvcs are not recreated by the upgrade

**Comment by friedrichwilken** [comment]
Here is a PR https://github.com/kyma-project/nats-manager/pull/127
