### ISSUE TITLE
Fix/Triage security issues for nats-manager

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/nats-manager#124]
**Tasks:**
- [x] Bump the nats-manager image to latest from main in [security-scan-config](https://github.com/kyma-project/nats-manager/blob/main/sec-scanners-config.yaml).
- [x] Ask/wait for security scans to run.
- [x] Fix/triage the security issues; check the following sections in the `Security Dashboard`:
   - [x] Checkmarx Modular Beta 
   - [x] Black Duck Binary Analysis Modular Beta
