### ISSUE TITLE
Check if the default CR is correct for kyma upgrade to nats-manager

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/nats-manager#125]
When we enable a module using `kyma alpha enable module nats -c fast -n kyma-system`, the lifecycle manager by default creates a NAT CR in the cluster. The default CR is configured [here](https://github.com/kyma-project/nats-manager/blob/main/config/samples/default.yaml).

**Task(s):**
- [ ]  Make sure that the default CR is correct for upgrade from kyma to nats-manager.
- [ ]  Test the changes:
   - [ ]  Follow these [steps](https://github.com/kyma-project/nats-manager/issues/77) to verify the upgrade.
   - [ ]  Fast-integration test
   - [ ] Stream and consumers are not recreated by the upgrade
   - [ ] Check that the pvcs are not recreated by the upgrade

**Comment by grischperl** [comment]
It will be covered in another ticket.
