### ISSUE TITLE
[EPIC] NATS-manager

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#14]
**Description**

NATS Manager is meant to be a standalone module for kyma. Its purpose is to deploy a working NATS cluster (with enabled Jetstream server) into the kyma cluster.
The configuration is setup to be used as an eventing backend. Configuration options that will prevent this cluster from being used as an eventing backend will not be available to the user. Some options that will not conflict with this requirement will be exposed to the user, so that the user can use this NATS cluster for implementation of non kyma-eventing workflows.

**Tasks:**
- [x] kyma-project/nats-manager#5
- [x] kyma-project/nats-manager#6
- [x] kyma-project/nats-manager#7
- [x] kyma-project/nats-manager#3
- [x] https://github.com/kyma-project/nats-manager/issues/8
- [x] #39
- [x] #79
- [x] #52
- [x] #92
- [x] #71
- [x] #142
- [x] #143
- [x] #144

**Optional Tasks:**
- [x] #68
- [ ] [Proposal] Should we have a `configMap` for all configurations for NATS-manager instead of ENV?
   - [ ] Make some settings in `HelmRenderer.newTemplatingAction()` configurable. ([reference](https://github.com/kyma-project/nats-manager/pull/17#discussion_r1151960108))
- [ ] Make the member variables of struct `ReleaseInstance` and `ManifestResource` private. ([reference]

**Duplicates:**
- [x] kyma-project/nats-manager#4
