### ISSUE TITLE
Cannot delete NATS as stream exists

### ISSUE THREAD

**Issue by grischperl** [kyma-project/nats-manager#143]
## Description
Once the NATS module is installed on a cluster, it cannot be deleted even though there are no subscriptions. Upon trying to delete the NATS module, the module remains in the status `Deleting` with the Error Message:
```
Cannot delete NATS as stream exists.
```
A SAP stream exists right from the beginning.

### Steps to recreate
- Create a cluster
- Enable the Kyma Environment
- Enable the NATS module
- Delete the NATS module
--> NATS module is stuck in deletion

## ToDo:
- [ ] What are the different ways to delete the module via UI and how do they differ?
- [ ] NATS module can be removed even if SAP stream exists.
- [ ] Update state accordingly.

## Acceptance
- [ ] NATS module can be removed when only SAP stream exists and no consumer exist on the stream.
- [ ] If the module cannot be deleted, the state should be set to `Warning`.
