### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by grischperl** [kyma-project/nats-manager#212]
## Description
The NATS Manager uses `mermaid` scripts in the [documentation](https://kyma-project.io/#/nats-manager/user/01-manager?id=module-lifecycle). The scripts are not rendered as graphs but show up as the code-behind. Additionally, some inconsistent naming and titles need to be corrected. The Status table in the Configuration doc does not render correctly.

## ToDo:
- [x] Create proper images out of the `mermaid` graphs and upload these to the documentation (https://github.com/kyma-project/nats-manager/pull/227)
- [ ] Make all titles sentence case (check for latest guidelines with @kyma-project/technical-writers )
- [ ] Rename `_sidebar` file to be the same as the corresponding page title
- [ ] Fix the inconsistent naming, only these two namings are correct: (no article) NATS Manager and the NATS module
~~- [ ] Fix the Status table in the[ Configuration doc](https://kyma-project.io/#/nats-manager/user/02-configuration), as this table is auto generated, try to fix the root cause. (Note: Same problem exists in the Eventing Manager)~~
