### ISSUE TITLE
Create Module Documentation

### ISSUE THREAD

**Issue by grischperl** [kyma-project/nats-manager#79]
**Description**
Currently, there is only one README file that has not yet been reviewed by the technical writers. The official module documentation is missing as well.

**Tasks**
- [x] Create a small change on the README and have the technical writers assigned (see [this PR](https://github.com/kyma-project/nats-manager/pull/87))
- [x] Check how other modules (KEDA and Telemetry) did the official module documentation -> [Checklist for each module](https://github.com/kyma-project/kyma/issues/16421)
- [x] Decide on how our module shall be documented and write the official module documentation
- [x] Find out how the OSS documentation shall look like and write the OSS documentation -> [OS documentation](https://github.tools.sap/kyma/community/issues/180) will be linked from the same repo as the official module documentation

**AC - copied**

- [x] Your audience is the end-user so the documentation must be written for them (not for the team that builds this module, or other SAP teams that wish to build a module, not for SRE, etc)
- [x] The documentation must be consumable by the kyma-project.io home page (split into several information types/md files)
- [x] Create a docs folder following the standard structure proposed in -> [Propose a standard structure for each module docs folder](https://github.com/kyma-project/kyma/issues/16775)
- [x] In each module's documentation include:
  - [x]  General description of the functionality (if the module is mandatory, mention it!)
  - [x]  Getting Started - instructions on how to use the module. The module docs must mention the prerequisite that the module must be enabled. They must also include instructions on how to install/enable a module.
  - [x] Module configuration
  - [x] Instructional documents (currently called "dev tutorials" and "operational guides") - must be isolated, i.e. no dependencies on other tutorials or modules. An example.
  - [x] If needed, troubleshooting
  - [x] Instructions on how to give feedback
